[package]
name = "rusty_llm"
version = "0.3.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.8.0"}
env_logger = { version = "0.11.3" }
lazy_static = { version = "1.5.0" }
llama_cpp = { version="0.3.2", features = ["clblast"]}  # using OpenCL for GPU offload is suboptimal as this only offloads the matrix multiplications atm.
log = { version = "0.4.22" }
prometheus = { version = "0.13.4" }
serde_json = { version = "1.0.121" }
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.39.2" }

[lib]
name = "rusty_llm"
path = "src/lib.rs"
doctest = false
